# Generated by Django 3.2.15 on 2022-09-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220905_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='teacher',
        ),
    ]
