# Generated by Django 3.2.15 on 2022-09-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220906_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
