# Generated by Django 3.2.15 on 2022-09-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_teacher_city_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='ClassName',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='class_name',
        ),
    ]
